spring:
  application:
    name: test-validations
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/user_data
      username: postgres
      password: trainibit
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
        group-id: consumer-group
logging:
  level:
    org:
      apache:
        kafka: ERROR
      springframework:
        kafka: ERROR
server:
  port: 8082