CREATE TABLE public.user_data (
                                  id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  email varchar NOT NULL,
                                  "uuid" uuid NOT NULL,
                                  template_uuid uuid NOT NULL,
                                  first_token varchar NOT NULL,
                                  created_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                  updated_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                  CONSTRAINT user_data_pk PRIMARY KEY (id)
);
